name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    paths-ignore: [ '.github/**' ]
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
      - '*.*.*'
  pull_request:
    paths-ignore: [ '.github/**' ]
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  ORGANIZATION: ${{ github.repository_owner }}
  SERVICE: ${{ github.event.repository.name }}

jobs:
  build-and-push-sourcemaps:
    name: Publish Source Maps
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build source maps
        run: yarn build

      - name: Get the version
        id: version
        run: echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Create Sentry release
        if: startsWith(github.ref, 'refs/tags/') && steps.version.outputs.version != '' && steps.version.outputs.version != 'undefined'
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./dist"
          version: ${{ secrets.SENTRY_PROJECT }}@${{ steps.version.outputs.version }}


  build-and-push-image:
    if: ${{ !(github.actor == 'dependabot[bot]' && github.repository_visibility == 'private') }}
    name: Publish Docker Image
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get Environment
        id: environment
        run: |
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            echo "name=production" >> $GITHUB_OUTPUT
          else
            echo "name=staging" >> $GITHUB_OUTPUT
          fi

      - name: Set lowercase organization and service names
        run: |
          ORGANIZATION_LC=$(echo '${{ env.ORGANIZATION }}' | tr '[:upper:]' '[:lower:]')
          SERVICE_LC=$(echo '${{ env.SERVICE }}' | tr '[:upper:]' '[:lower:]')

          echo "Setting environment variables for Docker image naming..."
          echo "IMAGE_NAME=$ORGANIZATION_LC/$SERVICE_LC" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{steps.environment.outputs.name}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }} # Push to registry for production/staging, not for PRs
          load: ${{ github.event_name == 'pull_request' }} # Load to local Docker for Trivy scan
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: ${{ steps.environment.outputs.name }}
          build-args:
            ENVIRONMENT=${{ steps.environment.outputs.name }}

      - name: Inspect Docker Image
        run: |
          echo "Inspecting Docker image..."
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} || true

      - name: Run Trivy vulnerability scanner
        if: ${{ github.event_name == 'pull_request' }} # Only run Trivy on pull requests
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          format: 'table'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
