name: Docker Linting
on:
  push:
    paths:
      - .github/workflows/docker-lint.yml
      - Dockerfile
      - .dockerignore

permissions:
  contents: read

jobs:
  dockerfile-lint:
    name: Lint Dockerfile
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile

  dockerignore-lint:
    name: Lint .dockerignore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Lint .dockerignore
        run: |
          DOCKERIGNORE_FILE=".dockerignore"
          if [ ! -f "$DOCKERIGNORE_FILE" ]; then
             echo "$DOCKERIGNORE_FILE does not exist."
             exit 1
          fi

          if ! grep -qE '^[^#].*' "$DOCKERIGNORE_FILE"; then
            echo "Error: .dockerignore file is empty or only contains comments."
            exit 1
          fi

          if ! grep -q '^.git$' "$DOCKERIGNORE_FILE"; then
            echo "Error: .dockerignore must contain the '.git' entry."
            exit 1
          fi
